### ISSUE TITLE
Server Restart Time

### ISSUE THREAD

**Issue by iPro36** [Stasadance/Germs.io#11]
The server restart timer is **counting up** instead of doing a **countdown**.
![capture](https://user-images.githubusercontent.com/38023207/38279485-8942ab6c-376e-11e8-8fd8-a506e782995b.PNG)

**Comment by Stasadance** [comment]
Any trigger to this happening? Does it happen right after a restart, etc? I can't reproduce it myself

**Comment by iPro36** [comment]
I believe that it happens right after the restart...

**Comment by Stasadance** [comment]
What time zone are you in? I still can't get it to happen at all, after a restart the game resets the timer for me

**Comment by iPro36** [comment]
Well, I am in est but it seems to be not a problem anymore.

**Comment by Stasadance** [comment]
Ok closing for now
