### ISSUE TITLE
Wrong Play Count

### ISSUE THREAD

**Issue by iPro36** [Stasadance/Germs.io#13]
The player count for **Main FFA** and ** Self-feed** is wrong. The number of players shown on the counter are 60-70% more than there are in-game.

Here is the **counter** for **main ffa** on the **server list**:
![capture](https://user-images.githubusercontent.com/38023207/38442525-974aa9d6-39b6-11e8-9457-67b56c265575.PNG)

Here are the **Number of Players** in the game on **main ffa**:
![capture2](https://user-images.githubusercontent.com/38023207/38442532-9afb2498-39b6-11e8-8a76-7753f4cf06eb.PNG)

Here is the **counter** for **self-feed** on the **server list**:
![capture3](https://user-images.githubusercontent.com/38023207/38442535-9e250742-39b6-11e8-837e-2e611017f52d.PNG)

Here are the **Number of Players** in the game on **self-feed**:
![capture4](https://user-images.githubusercontent.com/38023207/38442537-9f4c2056-39b6-11e8-95e7-e1b7ed2f732d.PNG)

**Comment by Stasadance** [comment]
That count is for all the individual servers combined, at the time of that picture main ffa had 3 servers with 30-40 players each

**Comment by iPro36** [comment]
Gotcha
