### ISSUE TITLE
GERMS IS DOWN... AGIAN!

### ISSUE THREAD

**Issue by iPro36** [Stasadance/Germs.io#14]
...

**Comment by iPro36** [comment]
Never mind its back up...

**Comment by iPro36** [comment]
It's down again!

**Comment by Stasadance** [comment]
This is an ongoing bug, i monitor it constantly to make sure it restarts properly, but something is up with the database that is causing Germs.io to crash every once in a while.

**Comment by iPro36** [comment]
Gotcha
